# Top Level is Releases attribute
# Under release I can define a lists of all the releases I want to deploy
# Each release has a name, chart, values, and namespace
releases: 
  # - name: the release name
  - name: rediscart
    # chart: the chart folder itself
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/redis
    # values: the values file to use
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/redis-values.yaml
      # I can also overide the values in the values file
      - appReplicas: "1"
      - volumeName: "redis-cart-data"
    # namespace: the namespace to deploy to
    namespace: microservices

  # Email Service
  - name: emailservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/email-service-values.yaml
    namespace: microservices

  # Ad Service 
  - name: adservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/ad-service-values.yaml
    namespace: microservices

  # Cart Service
  - name: cartservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/cart-service-values.yaml
    namespace: microservices

  # Checkout Service
  - name : checkoutservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/checkout-service-values.yaml
    namespace: microservices

  # Currency Service
  - name: currencyservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/currency-service-values.yaml
    namespace: microservices

  # Frontend Service
  - name: frontend
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/frontend-service-values.yaml
    namespace: microservices
  
  # Payment Service
  - name: paymentservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/payment-service-values.yaml
    namespace: microservices

  # Product Catalog Service
  - name: productcatalogservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/productcatalog-service-values.yaml
    namespace: microservices

  # Recommendation Service
  - name: recommendationservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/recommendation-service-values.yaml
    namespace: microservices

  # Shipping Service
  - name: shippingservice
    chart: Documents/Devops/Kubernetes/Create-HelmChart-Microservices/charts/microservices
    values:
      - Documents/Devops/Kubernetes/Create-HelmChart-Microservices/values/shipping-service-values.yaml
    namespace: microservices
